Upstream name change: Riot is now Element
aperezdc/revolt pull request #107
Opened 2020-07-23 15:56 UTC by joukewitteveen

I replaced `riot` by `element` throughout. This fixes #106.
Now that Riot is Element, the name Revolt has a historical origin :-).

2020-09-27 01:22 UTC, TheEvilSkeleton commented on README.md
> +Revolt is a small application which wraps [Element](https://element.im) to
```diff
-  Revolt is a small application which wraps [Element](https://element.im) to 
+  Revolt is a small application which wraps [Element](https://element.io) to 
```
The website is https://element.io/

2020-09-28 06:52 UTC, aperezdc requested changes
Patch looks good, thanks for sending it! I have a small comment about the settings key names, could you please take a look at that? :smiley:

2020-09-28 06:52 UTC, aperezdc commented on org.perezdecastro.Revolt.gschema.xml
> -		<key name="riot-url" type="s">
I think it's better to _not_ change the name of the settings key. It's not user-visible, and changing it will break people's settings.

The other option is rename the setting but write some code to migrate old settings... but given that the user will never see this in the user interface, it seems better to skip renaming the settings.

Could you please update the patch to not rename the settings? Thanks!

2020-09-30 19:15 UTC, joukewitteveen commented on org.perezdecastro.Revolt.gschema.xml
> -		<key name="riot-url" type="s">
Good point, done.

2020-09-30 21:51 UTC, aperezdc approved these changes
Thanks for the update, this looks good to merge now :muscle:

2020-09-30 21:51 UTC, merged